"""Generate a UV-sphere Wavefront OBJ with position + normal attributes.

Usage:
    python tools/gen_sphere.py [output_path]

Default output: sandbox/res/models/sphere.obj
"""

import math
import os
import sys


def generate(path: str, radius: float = 0.8, lats: int = 32, lons: int = 64) -> None:
    vertices = []
    for i in range(lats + 1):
        theta = math.pi * i / lats
        sin_t, cos_t = math.sin(theta), math.cos(theta)
        for j in range(lons):
            phi = 2.0 * math.pi * j / lons
            x = radius * sin_t * math.cos(phi)
            y = radius * cos_t
            z = radius * sin_t * math.sin(phi)
            vertices.append((x, y, z))

    with open(path, "w", encoding="utf-8") as f:
        f.write("# UV sphere generated by tools/gen_sphere.py\n")
        for x, y, z in vertices:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")

        # A unit sphere centered at the origin has normal == normalized position.
        for x, y, z in vertices:
            length = math.sqrt(x * x + y * y + z * z) or 1.0
            f.write(f"vn {x / length:.6f} {y / length:.6f} {z / length:.6f}\n")

        for i in range(lats):
            for j in range(lons):
                jn = (j + 1) % lons
                a = i * lons + j + 1
                b = i * lons + jn + 1
                c = (i + 1) * lons + jn + 1
                d = (i + 1) * lons + j + 1
                f.write(f"f {a}//{a} {b}//{b} {c}//{c}\n")
                f.write(f"f {a}//{a} {c}//{c} {d}//{d}\n")

    print(f"wrote {path}")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "sandbox/res/models/sphere.obj"
    radius = float(sys.argv[2]) if len(sys.argv) > 2 else 0.8
    lats = int(sys.argv[3]) if len(sys.argv) > 3 else 32
    lons = int(sys.argv[4]) if len(sys.argv) > 4 else 64
    os.makedirs(os.path.dirname(out), exist_ok=True)
    generate(out, radius, lats, lons)
